### ISSUE TITLE
StickyHeader on scrolling

### ISSUE THREAD

**Issue by stefancvetkovic** [AndreiMisiukevich/Instagramarin#1]
Hello Andrei again!
I like your examples and this one looks awesome!
However, I have a question regarding my case how to implement AbsoluteLayout on it..
Here is my example video [https://drive.google.com/file/d/1cKeJmc8Arnp3haXF77mpECIX9R_QH_48/view](example)
So basically, I do not have "Profile Part" I have sticky header (absoluteLayout) on startup of a page.
So I need just to change height on scrolling event of the list.
Can you point me what should I change to have such behavior? Spasiba!

**Comment by AndreiMisiukevich** [comment]
Hi, this is a very good question.
Perhaps you can handle it by putting both into StackLayout and you will
change height of your top view if ListView scrolled.


*Andrei Misiukevich*

*Lead Software Engineer at ISsoft Solutions*



*mobile: *+375 29 <+375%2017%20389%200100>303 40 07   Email:
andrei.misiukevich@gmail.com Skype: csi.andreymisyukevich

*Minsk,* *Belarus *(GMT+3)

**Comment by stefancvetkovic** [comment]
I just find zour another repo for this - Profile Screen. I will close this issue here!
